### ISSUE TITLE
Scoring total and other ideas

### ISSUE THREAD

**Issue by mg3point** [arim215/nhl_goal_light#22]
First of all thanks for this, I've been looking for a trigger for my Ambilight goal lights for awhile now. Favorite team affiliations aside, i had a few thoughts on what you have here.

In looking at your code for the score it looks as though you set the score back to zero if the new_score is less than old_score. I'm curious how this functions on disallowed goals? I question because I am a Bluejackets fan and the third goal of home games is the chili goal (everyone gets free chili with ticket stub the next day). Nothing crazy but the goal horn/song is different for it. So theoretically i would listen for score and tally it up and play one goal song for each unless it is the 3rd goal in which it would get a special case. Could you perhaps have some form of time based reset by way of after first score update trigger a score reset 8 hours later? (long enough to not obstruct current game, short enough to be reset before a back to back game.)

Another piece i am thinking about adding to what you have is listening for the powerplay. I see it is a var in the api. Depending on when it gets set to true, it could be fun to have a separate audio clip to play. (in arena announcer "Jackets....Ooooonnnnnnn theeeeee POWERPlaaaaaaaaay")

Lastly a piece to possibly implement would be a period beginning soon warning. Intermissions are 18 minutes. You could listen for the end of the period and call an audio que to happen in 15 minutes to give you a 3 minute warning.

I'm not a heavy backend developer. I am an interaction designer by day, but i love to tinker and have hacked my way this far with my goal light setup. This is an older video and it now runs on a separate pi but you can see my "faked trigger" light effect. (...if you were curious...) https://youtu.be/r_088QRyY-s?t=84

Thanks again and great work!

Mike

**Comment by arim215** [comment]
Hello and thank you for commenting. (I'd like to say that i watched your video a long time ago when i started my goal light project! Really like how the light behind the tv rotate!) 

You bring very interesting points. I will fix the reset to zero for new game, since i now detect end of games. So ill put the reset score with the end of game. 

For the

**Comment by arim215** [comment]
Hello and thank you for commenting. (I'd like to say that i watched your video a long time ago when i started my goal light project! Really like how the light behind the tv rotate!) 

You bring very interesting points. I will fix the reset to zero for new game, since i now detect end of games. So ill put the reset score with the end of game. 

For the disallowed goal... i've only encountered it once and the way it worked out was  : the goal went in, but the NHL didn't add it to the API i used cause it was being reviewed (i guess they dont post goals where there is a good enough doubt. But i'd have to think how to go back 1 goal in case a goal is disallowed.

For the special 3rd goal horn, that shouldn't be too hard (i don't think ill add it to my code since it's a special case... the Canadians have a 5goals = chicken wings...!) but i could send you the code you'd need to add to get it...

I never looked into the powerplay sound ... if it's in the api, can't be too hard... my only concern is how to make it sound once and not continuously (because i do a continuous loop to check api variables...)

and i haven't found a var in the api to tell me that the game is in intermission (i'll keep looking...) but it's a good idea.

But all those are all custom function that not EVERYONE would want... thus not sure if theyr are worth adding to my code, since it would make the setting up harder... but i'll think about it! 

Thanks a lot for the comment and i'll try to work soon on some of theses ideas!

**Comment by arim215** [comment]
@mg3point , commit a8889e0b0e4f5b4faa9cdf10d71a23e6520576e2 fixes goal disallowed and game reset score!

**Comment by arim215** [comment]
@mg3point , good news! i prepared you a code that would allow to have a special 3rd goal horn!

replace the light.py file in /lib folder with this one: 
[light.zip](https://github.com/arim215/nhl_goal_light/files/768147/light.zip)

make sure to have a "3rdgoal.mp3" in the /audio folder ... 

if anyone else wants to use this for a different team and different score, just change the team_id in the url and the var. and change the "if" compare value to the amount of goal to check. and place a "3rdgoal.mp3" in /audio folder or rename de "command_play_song" .mp3 to the name of the file

enjoy! ill try to keep working on your other requests and improvements

**Comment by mg3point** [comment]
Thanks for this, I really wasnt suggesting you HAD to do them, just some enhancements i was thinking of.

I was thinking about the PP issue of recalling it everytime and thoought about an if state set up like this...

////// Power Play Checker
////// based on api ("powerPlay" : false)
currentPPState = false;

if powerPlay == true {
    if curentPPState = false{
        PlayPPAudio()
        currentPPState = True;
    }
}
else {
    currentPPState = false;
}

as for the period timer, I saw something along the lines of ordinalNumber and end time you could perhaps use and compare to current time to decipher if the period was over then give it a 15 minute delay on the audio que.

Just some thoughts. Thanks again for your work on this. (hopefully i can get my other issue sorted out to get this working) Now if only the CBJ could wake back up and play good hockey again.

**Comment by arim215** [comment]
I looked in to this and there is no powerplay indication on "statsapi.web.nhl.com/api/v1/schedule?teamId=#". So I can't check for powerplay... for now I can't put more energy into this to find a more elaborate solution.  Same goes for the intermission.
